before_install: sudo apt-get install -y libtest-differences-perl
install: sh bootstrap.sh && sh configure && make && make check
language: c
compiler: gcc
env: TESTS_ENVIRONMENT=true XFAIL_TESTS=
script: prove && make dist-check
