before_install: sudo apt-get install -y libtest-differences-perl
install: sh bootstrap.sh
after_install: make uninstall 
language: c
compiler: gcc
env: TESTS_ENVIRONMENT=true XFAIL_TESTS=
script: sh configure && make && make check && prove && make dist-check
